name: DVF Pipeline (PROJET LDF)

on:
  schedule:
    - cron: "0 6 * * 1"  # chaque lundi à 6h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scrapy spider
        run: |
          cd src/scraper/dvf_scraper
          scrapy crawl dvf_spider

      - name: Run ingestion script
        run: python src/ingestion/download_dvf.py

      - name: Run cleaning script
        run: python src/cleaning/clean_dvf.py

      - name: Commit and push CSV
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Mise à jour automatique des données DVF"
          add: |
            data/dvf_clean.csv
            data/latest_url.txt